[tool.poetry]
name = "topo-processor"
version = "0.1.0"
description = ""
authors = ["Blayne Chard <bchard@linz.govt.nz>", "Megan Davidson <mdavidson@linz.govt.nz>", "Ben Cheng <BCheng@linz.govt.nz>"]

[tool.poetry.dependencies]
python = "^3.8"
linz-logger= "^0.2.0"
pystac= "^0.5.6"
py-multihash = "^2.0.1"
rasterio = "^1.2.1"
click = "^7.1.2"
boto3 = "^1.17.48"
ulid = "^1.1"
pytest-asyncio = "^0.14.0"
aiofiles = "^0.6.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.8.0"
pylint = "^2.7.4"
pytest = "^6.2.3"
rope = "^0.18.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 127

[tool.isort]
line_length = 127
case_sensitive = true
use_parentheses = true
include_trailing_comma = true
multi_line_output = 3
force_grid_wrap = 0
