[tool.poetry]
name = "topo-processor"
version = "0.1.0"
description = ""
authors = ["Blayne Chard <bchard@linz.govt.nz>", "Megan Davidson <mdavidson@linz.govt.nz>", "Ben Cheng <BCheng@linz.govt.nz>"]

[tool.poetry.dependencies]
python = "^3.8"
linz-logger= "^0.2.0"
pystac= "^0.5.2"
py-multihash = "^0.2.3"
aiocogeo = {extras = ["s3"], version = "^0.1.7"}

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.5.4"
pylint = "^2.6.0"
pytest = "^6.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 127

[tool.isort]
line_length = 127
case_sensitive = true
use_parentheses = true
include_trailing_comma = true
multi_line_output = 3
force_grid_wrap = 0
