name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Use Python "3.8"
        uses: actions/setup-python@v2.1.4
        with:
          python-version: "3.8"
      - name: Install
        run: |
          pip install poetry
          poetry install
      - name: Format
        run: |
          poetry run black . --check --diff
      - name: Lint
        run: |
          poetry run pylint topo_processor/ --exit-zero
      - name: Import Sorting
        run: |
          poetry run isort -rc . --check --diff
      - name: Test
        run: |
          poetry run pytest
