name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Use Python "3.8"
        uses: actions/setup-python@v2.1.3
        with:
          python-version: "3.8"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint Last Commit
        if: github.event_name == 'push'
        run: |
          gitlint
      - name: Format
        run: |
          black . --check --diff
      - name: Lint
        run: |
          pylint salutation.py test_salutation.py
      - name: Import Sorting
        run: |
          isort -rc . --check --diff
      - name: Test
        run: |
          pytest

